import type { Metadata } from 'next'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import { Inter } from 'next/font/google'
import { NuqsAdapter } from 'nuqs/adapters/next/app'

import './globals.css'
import { Toaster } from '@/components/ui/sonner'
import PremiumModal from '@/components/premium/premium-modal'
import Script from 'next/script'
import { SubscriptionProvider } from './(protected)/resumes/_components/subscription-client'

const inter = Inter({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  return (
    <SessionProvider session={session}>
      <SubscriptionProvider>
        <html lang="en">
          <body className={`${inter.className} antialiased`}>
            <NuqsAdapter>
              <Toaster />
              <PremiumModal />
              <Script
                id="razorpay-checkout-js"
                src="https://checkout.razorpay.com/v1/checkout.js"
                strategy="beforeInteractive"
              />
              {children}
            </NuqsAdapter>
          </body>
        </html>
      </SubscriptionProvider>
    </SessionProvider>
  )
}
