export const SECTIONS = [
  'CONTACT',
  'EXPERIENCE',
  'PROJECT',
  'EDUCATION',
  'CERTIFICATIONS',
  'COURSEWORK',
  'INVOLVEMENT',
  'SKILLS',
  'SUMMARY',
  'FINISH UP & REVIEW',
  'AI COVER LETTER',
]
